version: "3"

networks:
  v2board:

services:
  www:
    image: stpog/v2board-docker
    volumes:
      - "<v2board-docker-data>/www:/www"
      - "<v2board-docker-data>/wwwlogs:/wwwlogs"
      - "<v2board-docker-data>/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
      - "<v2board-docker-data>/config/crontabs.conf:/etc/crontabs/root"
      - "<v2board-docker-data>/config/nginx.conf:/etc/nginx/nginx.conf"
      - "<v2board-docker-data>/config/nginx_v2board.conf:/etc/nginx/http.d/nginx_v2board.conf"
      - "<v2board-docker-data>/config/php-fpm.conf:/etc/php7/php-fpm.conf"
      - "<v2board-docker-data>/tls:/root/tls:ro"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - v2board
  mysql:
    image: mysql:5.7.29
    volumes:
      - "<v2board-docker-data>/mysql:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: YOURPASSWD
      MYSQL_DATABASE: v2board
    networks:
      - v2board
