version: "3"

volumes:
  v2board-data:
  db-data:


networks:
  v2board:


services:
  www:
    image: moefaq/v2board-lnrp-docker:dev
    volumes:
      - v2board-data:/data
      - "/etc/localtime:/etc/localtime"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      TZ: Asia/Shanghai
      DB_HOST: mysql
      DB_DATABASE: v2board
      DB_USERNAME: root
      DB_PASSWORD: YOURPASSWD
      ADMIN_EMAIL: dev@dev.dev
      LARAVEL_HORIZON_PROCS_NUM: 1
      NGINX_CERT_TEXT: |-
        -----BEGIN EC PRIVATE KEY-----
        exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exam
        pleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleE
        XAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMP
        LE123456exampleEXAMPLE123456exa=
        -----END EC PRIVATE KEY-----
      NGINX_KEY_TEXT: |-
        -----BEGIN CERTIFICATE-----
        exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exam
        pleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleE
        XAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMP
        LE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE12
        3456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456
        exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exam
        pleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleE
        XAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMP
        LE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE12
        3456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456
        exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exam
        pleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleE
        XAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMP
        LE123456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE12
        3456exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456
        exampleEXAMPLE123456exampleEXAMPLE123456exampleEXAMPLE123456exam
        pleEXAMPLE123456exampleEXAMPLE123456exampleEXAMP
        -----END CERTIFICATE-----
    networks:
      - v2board
  mysql:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
      - "/etc/localtime:/etc/localtime"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: YOURPASSWD
      MYSQL_DATABASE: v2board
    networks:
      - v2board
